#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  9 11:29:33 2022

@author: namnguyen
"""


def CARSEC_Writer(Dict,name='CARSEC'):
    with open(name+'.txt', 'w') as f:
        f.write('CARSEC'+' \n')
        f.write('secc '+Dict['secc']+' \n')
        f.write('unid '+Dict['unid']+' \n')
        f.write('norm '+Dict['norm']+' \n')
        f.write('coef horm '+Dict['coef horm']+' arma '+Dict['coef arma'] + ' pret '+Dict['coef pret']+  ' \n')

        f.write('punt '+str(Dict['punt'])+'\n')
        for k in Dict['punt'].keys():
            k1=str(Dict['punt'][k][0])
            k2=str(Dict['punt'][k][1])
            f.write(str(k)+' '+ k1+' ' + k2 +' \n')
            
        f.write('horm '+Dict['horm']+' \n')
        f.write('* punto contorno '+'\n')    
        [f.write(str(i)+' ') for i in Dict['punt contorno']] 
        f.write('\n')
                 
        f.write('hc ') 
        for k in Dict['hc'].keys():
            k1=str(Dict['hc'][k])          
            f.write( k1 +' ')
        f.write('\n')
        f.write('arma '+Dict['arma']+' \n')
        for k in Dict['punt armadura'].keys():
            k1=str(Dict['punt armadura'][k])          
            f.write( k1+' ')
        f.write('\n')
        f.write('calc inte'+' \n')
        for k in Dict['calc inte'].keys():
            k1=str(Dict['calc inte'][k])          
            f.write( k1+ ' ')
        f.write('\n')
        f.write('fin')
                         