#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  9 11:45:45 2022


@author: namnguyen
"""

import pandas as pd

                         
List_keys=['secc', 'unid', 'norm', 'coef horm', 'coef arma','coef pret','punt','horm','punt contorno','hc','arma', 'punt armadura','calc inte']